
CREATE TABLE CIDADE
(
	UKEY		CHAR(20) NOT NULL PRIMARY KEY, /*CHAVE UNICA PARA REFERENCIA*/
	CI_001_N	INT NOT NULL DEFAULT (0), /*ID IBGE*/
	CI_002_C	VARCHAR(2) NOT NULL DEFAULT (''), /*UF*/
	CI_003_C	VARCHAR(70) NOT NULL DEFAULT (''), /*NOME CIDADE*/
	CI_004_L	BIT NOT NULL DEFAULT (0), /*CAPITAL*/
	CI_005_C	VARCHAR(20) NOT NULL DEFAULT (''), /*LONGITUDE*/
	CI_006_C	VARCHAR(20) NOT NULL DEFAULT (''), /*LATITUDE*/
	CI_007_C	VARCHAR(70) NOT NULL DEFAULT (''), /*NOME DA CIDADE SEM ACENTUAÇÃO*/
	CI_008_C	VARCHAR(70) NOT NULL DEFAULT (''), /*NOME ALTERNATIVO*/
	CI_009_C	VARCHAR(70) NOT NULL DEFAULT (''), /*MICRO REGIÃO*/
	CI_010_C	VARCHAR(70) NOT NULL DEFAULT (''), /*REGIÃO USADA PARA MEDIR A DISTANCIA*/
)